### ISSUE TITLE
Implementar optimización del cifrado, haciéndolo multiproceso

### ISSUE THREAD

**Issue by manbuegom** [decide-single-chullo/decide#2]
Gestionar una optimización del cifrado actual para convertirlo en multiproceso.

**Comment by pabsanort2** [comment]
Se retrasa ya que la complejidad es mayor de lo que se esperaba, he estado revisando el algoritmo de cifrado pero no consigo encontrar las partes del código donde se llaman al mismo. Se replanifica para el M3.

**Comment by alebangon** [comment]
Help wanted: Me he asignado para ayudar a la issue y estoy intentando el desarrollo

**Comment by manbuegom** [comment]
Se pasa a To Do por decisión de no abordar la tarea y realizar alguna otra, debido a la dificultad de la misma. Se añade la etiqueta de won't fix y se dejará ahí.
