### ISSUE TITLE
Implementar página de inicio de cabina

### ISSUE THREAD

**Issue by alebangon** [decide-single-chullo/decide#37]
Se pretende implementar una página de inicio en la que, al hacer log in, salgan todas las votaciones disponibles, es decir, que el usuario esté en el censo, que la votación esté empezada y no parada y que no haya votado todavía.

**Comment by manbuegom** [comment]
La feature en cuestión no se abordara. Esta feature quedará sin desarrollarse y hay otra en sustitución. Se cierra y se deja fuera del proyecto, con su etiqueta won't fix correspondiente.
