### ISSUE TITLE
Incidencia: Error en los tests de voting

### ISSUE THREAD

**Issue by pabsanort2** [decide-single-chullo/decide#53]
Se ha detectado un fallo al correr los tests de selenium en la clase de tests de voting. 

Para replicar el problema habria que ejecutar el comando ./manage.py test voting

Revisor: josmarsan24

**Comment by manbuegom** [comment]
Issue creada por error. Trataba de reportarse un problema que no existía debido a una confusión entre compañeros. Se cierra la issue ya que no se va a abordar la incidencia.
