### ISSUE TITLE
Incidencia: Corregir test de selenium de mensaje de tally

### ISSUE THREAD

**Issue by alebangon** [decide-single-chullo/decide#67]
Al ejecutar el test "test_mensaje_tally()" del módulo de votaciones da un error ya que había cosas implementadas en develop, este error se arreglará adecuandolo a las nuevas implementaciones y añadiendo los assert correspondientes al mensaje.

Para replicar el error basta con ejecutar los tests de voting y se observará el error.

Revisor: Enrique González boza

**Comment by manbuegom** [comment]
No se realizará la issue, se le añade la etiqueta y se saca del proyecto. Además. se cierra.

**Comment by manbuegom** [comment]
Cerrada por error, se vuelve a trabajar en ella (bug).
